#ifndef IVFDFIREDETECT_GLOBAL_H
#define IVFDFIREDETECT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef IVFDFIREDETECT_LIB
# define IVFDFIREDETECT_EXPORT Q_DECL_EXPORT
#else
# define IVFDFIREDETECT_EXPORT Q_DECL_IMPORT
#endif

#endif // IVFDFIREDETECT_GLOBAL_H
